@startuml
start 
while (Юзер поставил предмет на отслеживание?) is (нет)
:Ждем комманды юзера;
endwhile (Да)
if (Предмет существует) then (Да)
:начинаем отслеживать цену на предммет;
else (нет) 
: Уведомление об ошибке;
stop

while (Цена ниже или равна необходимой) is (Нет)
:Ждем понижения цены;
endwhile (Да)
:Отправляем уведомление пользователю;
@enduml
