version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "WarframeMarket"
      POSTGRES_USER: "MaksA"
      POSTGRES_PASSWORD: "admin12345"
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U MaksA -d WarframeMarket"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "MaksA@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin12345"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    profiles:
      - pgadmin
volumes:
  db-volume:
  pgadmin-data:  