@startuml

[*] --> State1
State1 : Начало отслеживания Предмета

State1 -> State2 
State2 : Отслеживание цены
State2 -> [*] : Пользователь удалил Предмет
State2 -> State3 : Цена удолетворяет условиям отслеживания
State3 : Отправить уведомление пользователю 

@enduml
